import SeederView from "./view/seeder_view";
import seederProvinsi from "./data/area_provinsi.json"
import seederKabupaten from "./data/area_kabkot.json"
import seederKecamatan from "./data/area_kecamatan.json"
import seederDesa1 from "./data/area_desa_1.json"
import seederDesa2 from "./data/area_desa_2.json"
import seederDesa3 from "./data/area_desa_3.json"
import seederLeader from "./data/category_leader_trait_assessment.json"
import seederPublic from "./data/category_public_concern_trend.json"
import seederComponents from "./data/component.json"
import seederUserRole from "./data/user_role.json"
import seederUserAccess from "./data/user_access.json"
import seederUser from "./data/user.json"

export { SeederView }
export { seederProvinsi }
export { seederKabupaten }
export { seederKecamatan }
export { seederDesa1 }
export { seederDesa2 }
export { seederDesa3 }
export { seederLeader }
export { seederPublic }
export { seederComponents }
export { seederUserRole }
export { seederUserAccess }
export { seederUser }