import ChartBangunanPermanen from "./ekonomi/components/chart_bangunan_permanen";
import ViewEkonomi from "./ekonomi/view/view_ekonomi";
import ViewLayoutTmp from "./global_layout/view/view_layout_tmp";
import ViewInfrastrukturAndTransportasi from "./infrastruktur_and_transportasi/view/view_infrastruktur_and_transportasi";
import ViewKamtibmas from "./kamtibmas/view/view_kamtibmas";
import ViewKeagamaan from "./keagamaan/view/view_keagamaan";
import ViewKemiskinanDanKetimpangan from "./kemiskinan_dan_ketimpangan/view/view_kemiskinan_dan_ketimpangan";
import ViewKesehatan from "./kesehatan/view/view_kesehatan";
import funDownloadJaminanHariTua from "./ketenagakerjaan/back/fun/download_jaminan_hari_tua";
import funDownloadJaminanKecelakaanKerja from "./ketenagakerjaan/back/fun/download_jaminan_kecelakaan_kerja";
import funDownloadJaminanKematian from "./ketenagakerjaan/back/fun/download_jaminan_kematian";
import funDownloadJaminanKesehatan from "./ketenagakerjaan/back/fun/download_jaminan_kesehatan";
import funDownloadJaminanPensiun from "./ketenagakerjaan/back/fun/download_jaminan_pensiun";
import funDownloadPengangguran from "./ketenagakerjaan/back/fun/download_pengangguran";
import funGetJaminanHariTua from "./ketenagakerjaan/back/fun/get_jaminan_hari_tua";
import funGetJaminanKecelakaanKerja from "./ketenagakerjaan/back/fun/get_jaminan_kecelakaan_kerja";
import funGetJaminanKematian from "./ketenagakerjaan/back/fun/get_jaminan_kematian";
import funGetJaminanKesehatan from "./ketenagakerjaan/back/fun/get_jaminan_kesehatan";
import funGetJaminanPensiun from "./ketenagakerjaan/back/fun/get_jaminan_pensiun";
import funGetPengangguran from "./ketenagakerjaan/back/fun/get_pengangguran";
import ViewJaminanHariTua from "./ketenagakerjaan/back/view/view_jaminan_hari_tua";
import ViewJaminanKecelakaanKerja from "./ketenagakerjaan/back/view/view_jaminan_kecelakaan_kerja";
import ViewJaminanKematian from "./ketenagakerjaan/back/view/view_jaminan_kematian";
import ViewJaminanKesehatan from "./ketenagakerjaan/back/view/view_jaminan_kesehatan";
import ViewJaminanPensiun from "./ketenagakerjaan/back/view/view_jaminan_pensiun";
import ViewPengangguran from "./ketenagakerjaan/back/view/view_pengangguran";
import ViewKetenagakerjaan from "./ketenagakerjaan/front/view/view_ketenagakerjaan";
import ViewPendidikan from "./pendidikan/view/view_pendidikan";
import ViewPertanian from "./pertanian/view/view_pertanian";

export { ViewLayoutTmp }
export { ViewKetenagakerjaan }
export { ViewInfrastrukturAndTransportasi }
export { ViewKeagamaan }
export { ViewPendidikan }
export { ViewKesehatan }
export { ViewKamtibmas }
export { ViewEkonomi }
export { ViewPertanian }
export { ViewKemiskinanDanKetimpangan }
export { ChartBangunanPermanen }
export { ViewJaminanKesehatan }
export { ViewJaminanKecelakaanKerja }
export { ViewJaminanKematian }
export { ViewJaminanHariTua }
export { ViewJaminanPensiun }
export { ViewPengangguran }
export { funDownloadJaminanKesehatan }
export { funGetJaminanKesehatan }
export { funDownloadJaminanKecelakaanKerja }
export { funGetJaminanKecelakaanKerja }
export { funGetJaminanKematian }
export { funDownloadJaminanKematian }
export { funGetJaminanHariTua }
export { funDownloadJaminanHariTua }
export { funGetJaminanPensiun }
export { funDownloadJaminanPensiun }
export { funGetPengangguran }
export { funDownloadPengangguran }